### ISSUE TITLE
Unusable Server response

### ISSUE THREAD

**Issue by faxe1008** [otrtool/otrtool#14] opened 2017-01-05 20:17 UTC
Hi,
the tool currently only yields "error unusable server response". I'm using the amd64 Linux Ubuntu version.

Thanks

**Comment by eshrdlu** [comment] 2017-01-07 18:24
Hello,
decryption works for me, so I cannot reproduce your problem.
If it persists, please post output from otrtool, else the issue can be closed.

**Comment by faxe1008** [comment] 2017-01-08 23:04
otrtool -x TheSimpsons.mpg.mp4.otrkey

Trying to contact server...
Server responded.
Length of response must be a multiple of 8.00000000  F7 AE 74 F0 1E 74 DB 41  42 F7 B0 3A 03 BE 3C EC  |..t..t.AB..:..<.|
00000010  41 37 D8 5F 35 0B C0 37  F4 20 7D EF 5D BA DF 7E  |A7._5..7. }.]..~|
00000020  B4 DC 2F 7B 07 70 C3                              |../{.p.         |
00000027

Server response is unuseable, exiting

That is the answer

**Comment by eshrdlu** [comment] 2017-01-10 23:28
Which exact version of otrtool do you use? It should be reported as the first line of output, for example: OTR-Tool, v1.2.0-4-ga313e64

There was a problem like this in 2014, when OTR had changed something, see issue #5.

**Comment by eshrdlu** [comment] 2017-09-09 17:00
Closed for now, possibly a duplicate of issue #5

**Closed by eshrdlu** 2017-09-09 17:00 UTC
